openapi: 3.0.0
info:
  title: seller-pages
  description: '–ë–µ–∫–µ–Ω–¥ –¥–ª—è –∞–Ω–¥—Ä–æ–π–¥ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏—è'
  version: 1.0.0
tags: [ ]
paths:
  /api/products:
    get:
      summary: –ü–æ–ª—É—á–µ–Ω–∏–µ —Å–ø–∏—Å–∫–∞ —Ç–æ–≤–∞—Ä–æ–≤
      description: '–ü–æ–ª—É—á–µ–Ω–∏–µ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ –æ —Ç–æ–≤–∞—Ä–∞—Ö –¥–ª—è –≥–ª–∞–≤–Ω–æ–≥–æ —ç–∫—Ä–∞–Ω–∞'
      parameters:
        - name: page
          in: query
          description: '–ù–æ–º–µ—Ä —Å—Ç—Ä–∞–Ω–∏—Ü—ã'
          required: false
          schema:
            type:
              integer
      tags: [ –¢–æ–≤–∞—Ä—ã ]
      responses:
        '200':
          description: '–£—Å–ø–µ—à–Ω—ã–π –æ—Ç–≤–µ—Ç'
          content:
            application/json:
              schema:
                type: object
                properties:
                  currentPage:
                    type: integer
                  totalPages:
                    type: integer
                  Data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MainPageProduct'
                required:
                  - currentPage
                  - totalPages
                  - Data
                example:
                  currentPage: 1
                  totalPages: 2
                  Data:
                    - id: ab19936e-9155-43d4-aaf7-6dacbdc668ce
                      name: –ö—Ä–µ–º –¥–ª—è —Ç–µ–ª–∞
                      article: 3080366669
                      category: –ö–æ—Å–º–µ—Ç–∏–∫–∞
                      imageUrl: basket-17.wbbasket.ru/vol2679/part267903/267903164/images/big/1.webp
                      isRemovable: true
                      oldPrice: 670.1064369190367
                      price: 416.8376802162891
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
      security:
        - bearerHttpAuthentication: []
  /api/products/generate:
    post:
      summary: –°–æ–∑–¥–∞–Ω–∏–µ —Ç–æ–≤–∞—Ä–∞
      description: '–ú–µ—Ç–æ–¥ –¥–æ–±–∞–≤–ª—è–µ—Ç –Ω–æ–≤—ã–π —Ç–æ–≤–∞—Ä –≤ –±–∞–∑—É –∏ –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ —Ç–æ–≤–∞—Ä–µ –¥–ª—è –≥–ª–∞–≤–Ω–æ–≥–æ —ç–∫—Ä–∞–Ω–∞'
      tags: [ –¢–æ–≤–∞—Ä—ã ]
      responses:
        '200':
          description: '–£—Å–ø–µ—à–Ω—ã–π –æ—Ç–≤–µ—Ç, —Ç–æ–≤–∞—Ä –¥–æ–±–∞–≤–ª–µ–Ω'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MainPageProduct'
              example:
                id: ab19936e-9155-43d4-aaf7-6dacbdc668ce,
                name: –ö—Ä–µ–º –¥–ª—è —Ç–µ–ª–∞,
                article: 3080366669,
                category: –ö–æ—Å–º–µ—Ç–∏–∫–∞,
                imageUrl: basket-17.wbbasket.ru/vol2679/part267903/267903164/images/big/1.webp,
                isRemovable: true,
                oldPrice: 670.1064369190367,
                price: 416.8376802162891
          headers: { }
        '401':
          $ref: '#/components/responses/401'
      security:
        - bearerHttpAuthentication: [ ]
  /api/products/{id}:
    get:
      summary: –ü–æ–ª—É—á–µ–Ω–∏–µ –ø–æ–ª–Ω–æ–π –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ –æ —Ç–æ–≤–∞—Ä–µ
      tags: [ –¢–æ–≤–∞—Ä—ã ]
      security:
        - bearerHttpAuthentication: [ ]
      parameters:
        - name: id
          in: path
          description: 'ID —Ç–æ–≤–∞—Ä–∞, –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ –∫–æ—Ç–æ—Ä–æ–º –Ω—É–∂–Ω–æ –ø–æ–ª—É—á–∏—Ç—å'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '–£—Å–ø–µ—à–Ω—ã–π –æ—Ç–≤–µ—Ç'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  article:
                    type: string
                  category:
                    type: string
                  description:
                    type: string
                  imageUrl:
                    type: string
                  oldPrice:
                    type: number
                  price:
                    type: number
                  rating:
                    type: number
                  warehouseQuantity:
                    type: integer
                  ordersCount:
                    type: integer
                required:
                  - id
                  - name
                  - article
                  - category
                  - description
                  - imageUrl
                  - price
                  - rating
                  - warehouseQuantity
                  - ordersCount
                example:
                  id: ab19936e-9155-43d4-aaf7-6dacbdc668ce
                  name: –ö—Ä–µ–º –¥–ª—è —Ç–µ–ª–∞
                  article: 3080366669
                  category: –ö–æ—Å–º–µ—Ç–∏–∫–∞
                  description: –ù–∞–≤–µ—Ä–Ω—è–∫–∞, –≤–∞–º –Ω–µ —Ö–≤–∞—Ç–∞–ª–æ –∏–º–µ–Ω–Ω–æ —ç—Ç–æ–≥–æ —Ç–æ–≤–∞—Ä–∞ –≤ –≤–∞—à–µ–π –∫–æ–ª–ª–µ–∫—Ü–∏–∏. –°—Ç–∞–≤ –æ–±–ª–∞–¥–∞—Ç–µ–ª–µ–º –¥–∞–Ω–Ω–æ–π –ø–æ–∑–∏—Ü–∏–∏ –≤—ã –∑–∞–±—É–¥–µ—Ç–µ —á—Ç–æ —Ç–∞–∫–æ–µ —Å–∫—É–∫–∞. –ë–µ—Ä–∏—Ç–µ, –Ω–µ –ø–æ–∂–∞–ª–µ–µ—Ç–µ!üêà
                  imageUrl: basket-17.wbbasket.ru/vol2679/part267903/267903164/images/big/1.webp,
                  oldPrice: 670.1064369190367
                  price: 416.8376802162891
                  rating: 0.022385660727388592
                  warehouseQuantity: 646
                  ordersCount: 903
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
    delete:
      summary: –£–¥–∞–ª–µ–Ω–∏–µ —Ç–æ–≤–∞—Ä–∞
      deprecated: false
      description: '–£–¥–∞–ª–∏—Ç—å –º–æ–∂–Ω–æ —Ç–æ–ª—å–∫–æ —É–¥–∞–ª—è–µ–º—ã–π —Ç–æ–≤–∞—Ä, –æ–±—Ä–∞—Ç–∏—Ç–µ –≤–Ω–∏–º–∞–Ω–∏–µ –Ω–∞ –ø–æ–ª–µ isRemovable'
      tags: [ –¢–æ–≤–∞—Ä—ã ]
      parameters:
        - name: id
          in: path
          description: 'ID —Ç–æ–≤–∞—Ä–∞, –∫–æ—Ç–æ—Ä—ã–π –Ω—É–∂–Ω–æ —É–¥–∞–ª–∏—Ç—å'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: '–¢–æ–≤–∞—Ä —É—Å–ø–µ—à–Ω–æ —É–¥–∞–ª–µ–Ω'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
      security:
        - bearerHttpAuthentication: [ ]
  /api/feedbacks:
    get:
      summary: –ü–æ–ª—É—á–µ–Ω–∏–µ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ –æ–± –æ—Ç–∑—ã–≤–∞—Ö –æ —Ç–æ–≤–∞—Ä–∞—Ö
      deprecated: false
      description: ''
      tags: [ –û—Ç–∑—ã–≤—ã ]
      parameters:
        - name: page
          in: query
          description: '–ù–æ–º–µ—Ä —Å—Ç—Ä–∞–Ω–∏—Ü—ã'
          required: false
          schema:
            type:
              integer
      responses:
        '200':
          description: '–£—Å–ø–µ—à–Ω—ã–π –æ—Ç–≤–µ—Ç'
          content:
            application/json:
              schema:
                type: object
                properties:
                  currentPage:
                    type: integer
                  totalPages:
                    type: integer
                  Data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        rating:
                          type: number
                        ordersCount:
                          type: integer
                        refundsPercent:
                          type: number
                        feedbacks:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                              buyerName:
                                type: string
                              rating:
                                type: integer
                              pros:
                                type: string
                              cons:
                                type: string
                              comment:
                                type: string
                              photosURL:
                                type: array
                                items:
                                  type: string
                              isRefund:
                                type: boolean
                            required:
                              - id
                              - buyerName
                              - rating
                              - pros
                              - cons
                              - comment
                              - photosURL
                              - isRefund
                      required:
                        - id
                        - name
                        - rating
                        - ordersCount
                        - refundsPercent
                        - feedbacks
                required:
                  - currentPage
                  - totalPages
                  - Data
                example:
                  currentPage: 1
                  totalPages: 2
                  Data:
                    - id: 6b53087b-edf9-4898-a4b1-91531dfb3dab
                      imageUrl: basket-19.wbbasket.ru/vol3178/part317854/317854683/images/big/1.webp
                      name: –ö—Ä–µ–º –¥–ª—è —Ç–µ–ª–∞
                      rating: 2.9426452906136187
                      ordersCount: 897,
                      refundsPercent: 45.83424644529311
                      feedbacks:
                        - id: 554e46dc-0986-44c7-8889-1f2d670021d1
                          buyerName: –ê–Ω–Ω–∞ –ü–µ—Ç—Ä–æ–≤–∞
                          rating: 3
                          pros: –£–ø–∞–∫–æ–≤–∫–∞ –±—ã–ª–∞ –∞–∫–∫—É—Ä–∞—Ç–Ω–æ–π –∏ –ø–ª–æ—Ç–Ω–æ–π
                          cons: –¶–µ–Ω–∞ –∫–∞–∂–µ—Ç—Å—è —Å–ª–µ–≥–∫–∞ –∑–∞–≤—ã—à–µ–Ω–Ω–æ–π
                          comment: –ü–æ —Å—Ä–æ–∫—É —Å–ª—É–∂–±—ã —Å–ª–æ–∂–Ω–æ —Å–∫–∞–∑–∞—Ç—å, –ø–æ–ø–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è –Ω–∞–¥–æ, –æ—Ç–∑—ã–≤ –±—É–¥–µ—Ç –¥–æ–ø–æ–ª–Ω—è—Ç—å—Å—è.
                          photosURL:
                            - basket-17.wbbasket.ru/vol2679/part267903/267903164/images/big/1.webp
                          isRefund: false
        '401':
          $ref: '#/components/responses/401'
      security:
        - bearerHttpAuthentication: [ ]
  /api/balanceInfo:
    get:
      summary: –ü–æ–ª—É—á–µ–Ω–∏–µ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ –æ –±–∞–ª–∞–Ω—Å–µ –ø—Ä–æ–¥–∞–≤—Ü–∞
      deprecated: false
      description: ''
      tags: [ –ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ –±–∞–ª–∞–Ω—Å–µ ]
      security:
        - bearerHttpAuthentication: [ ]
      responses:
        '200':
          description: '–£—Å–ø–µ—à–Ω—ã–π –æ—Ç–≤–µ—Ç'
          content:
            application/json:
              schema:
                type: object
                properties:
                  shopId:
                    type: string
                  balance:
                    type: number
                  sales:
                    type: number
                  income:
                    type: integer
                  shopRating:
                    type: number
                  totalSalesCount:
                    type: integer
                  totalRefundsCount:
                    type: integer
                  salesChart:
                    type: object
                    properties:
                      averageSales:
                        type: number
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            amount:
                              type: integer
                            period:
                              type: string
                          required:
                            - amount
                            - period
                    required:
                      - averageSales
                      - data
                  totalRefundsPercent:
                    type: number
                  monthlyRatingGrow:
                    type: number
                  monthlySalesGrow:
                    type: integer
                required:
                  - shopId
                  - balance
                  - sales
                  - income
                  - shopRating
                  - totalSalesCount
                  - totalRefundsCount
                  - salesChart
                  - totalRefundsPercent
                  - monthlyRatingGrow
                  - monthlySalesGrow
                example:
                  "shopId": "2619f2da-b3cc-490e-81ad-105323448a78"
                  "balance": 574229.23
                  "sales": 97234.1
                  "income": 85001
                  "shopRating": 4.87
                  "totalSalesCount": 24336
                  "totalRefundsCount": 442
                  "salesChart":
                    "averageSales": 94078.03333333333
                    "data":
                      - "amount": 97234.1
                        "period": "–°–µ–Ω—Ç—è–±—Ä—å"
                  "totalRefundsPercent": 1.8162394
                  "monthlyRatingGrow": 0.04
                  "monthlySalesGrow": 44
        '401':
          $ref: '#/components/responses/401'
  /api/createTeacherToken:
    post:
      tags: [ –î–ª—è –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª–µ–π ]
      summary: –°–æ–∑–¥–∞—Ç—å —Ç–æ–∫–µ–Ω –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª—è
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
          description: –ò–º—è, –∫–æ—Ç–æ—Ä–æ–µ –±—É–¥–µ—Ç –∑–∞–ø–∏—Å–∞–Ω–æ –≤–Ω—É—Ç—Ä—å —Ç–æ–∫–µ–Ω–∞
      security:
        - bearerHttpAuthentication: [ ]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOi..."
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
  /api/createToken:
    post:
      tags: [ –î–ª—è –ø—Ä–µ–ø–æ–¥–∞–≤–∞—Ç–µ–ª–µ–π ]
      summary: –°–æ–∑–¥–∞—Ç—å —Ç–æ–∫–µ–Ω —Å—Ç—É–¥–µ–Ω—Ç–∞
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
          description: –ò–º—è, –∫–æ—Ç–æ—Ä–æ–µ –±—É–¥–µ—Ç –∑–∞–ø–∏—Å–∞–Ω–æ –≤–Ω—É—Ç—Ä—å —Ç–æ–∫–µ–Ω–∞
      security:
        - bearerHttpAuthentication: [ ]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOi..."
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
components:
  schemas:
    MainPageProduct:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        article:
          type: string
        category:
          type: string
        imageUrl:
          type: string
        isRemovable:
          type: boolean
        oldPrice:
          type: number
        price:
          type: number
      required:
        - id
        - name
        - article
        - category
        - imageUrl
        - isRemovable
        - price
      example:
        id: 6b53087b-edf9-4898-a4b1-91531dfb3dab
        name: –ö—Ä–µ–º –¥–ª—è —Ç–µ–ª–∞
        article: 9443845766
        category: –ö–æ—Å–º–µ—Ç–∏–∫–∞
        imageUrl: basket-19.wbbasket.ru/vol3178/part317854/317854683/images/big/1.webp
        isRemovable: true,
        price: 127.21859981085078
  responses:
    '400':
      description: '–ù–µ–≤–µ—Ä–Ω—ã–π –∑–∞–ø—Ä–æ—Å, –æ—à–∏–±–∫–∞ –≤ —Ñ–æ—Ä–º–∞—Ç–µ –ø–æ–ª—è pages'
      content:
        text/plain:
          schema:
            type: string
          example: 'bad request: invalid page number: strconv.Atoi: parsing "sdfd": invalid syntax'
    '401':
      description: '–¢–æ–∫–µ–Ω –¥–æ—Å—Ç—É–ø–∞ –Ω–µ–¥–µ–π—Å—Ç–≤–∏—Ç–µ–ª–µ–Ω –∏–ª–∏ –Ω–µ —É–∫–∞–∑–∞–Ω'
      content:
        text/plain:
          schema:
            type: string
          example: '401 Unauthorized'
    '403':
      description: '–û–ø–µ—Ä–∞—Ü–∏—è –∑–∞–ø—Ä–µ—â–µ–Ω–∞'
      content:
        text/plain:
          schema:
            type: string
          example: 'GetProductByID: forbidden: product is not removable'
    '404':
      description: '–ò—Å–∫–æ–º—ã–π –æ–±—ä–µ–∫—Ç –Ω–µ –Ω–∞–π–¥–µ–Ω'
      content:
        text/plain:
          schema:
            type: string
          example: 'GetProductByID: not found: product ab936e-9155-43d4-aaf7-6dacbdc668ce not found'
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer token using a JWT
      type: http
      scheme: Bearer
      bearerFormat: JWT
      in: header
      name: Authorization